---
- name: Prepare
  hosts: all
  tasks:
    - name: install os packages assumed to be pre-baked
      apt: name={{ packages }} state=present
      vars:
        packages:
          - iproute2
          - locales
          - openssh-server

    - name: ensure log files watched by fail2ban exist
      file: state=touch path={{ item }} owner=root group=root mode=0644
      when: ansible_distribution_release in ['xenial']
      loop:
        - /var/log/auth.log
        - /var/log/mail.log
        - /var/log/mail.warn
