---
- debug:
    msg: >-
      OwnCloud is no longer supported on Debian jessie
      https://github.com/sovereign/sovereign/issues/765
  when: ansible_distribution_release == "jessie"

- import_tasks: owncloud.yml
  tags: owncloud
  # https://github.com/sovereign/sovereign/issues/765
  when: ansible_distribution_release != "jessie"
